steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - hello_world
  - --source=.
  - --trigger-http
  - --trigger-bucket=buk-temp
  - --runtime=python37
  - --allow-unauthenticated
